name: afni
version: 24.3.00

copyright:
  - license: GPL-3.0
    url: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu20.html

architectures:
  - x86_64

build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - install:
        - software-properties-common
    
    - run:
        - add-apt-repository universe -y
    
    - install:
        - libgdal-dev
        - libopenblas-dev
        - libnode-dev
        - libudunits2-dev
        - r-base
        - r-base-dev
        - tcsh
        - xfonts-base
        - libssl-dev
        - python-is-python3
        - python3-matplotlib
        - python3-numpy
        - python3-flask
        - python3-flask-cors
        - python3-pil
        - gsl-bin
        - netpbm
        - gnome-tweaks
        - libjpeg62
        - xvfb
        - xterm
        - vim
        - curl
        - gedit
        - evince
        - eog
        - libglu1-mesa-dev
        - libglw1-mesa-dev
        - libxm4
        - build-essential
        - libcurl4-openssl-dev
        - libxml2-dev
        - libgfortran-14-dev
        - libgomp1
        - gnome-terminal
        - nautilus
        - firefox
        - xfonts-100dpi
        - r-base-dev
        - cmake
        - bc
        - libxext-dev
        - libxmu-dev
        - libxpm-dev
        - libgsl-dev
        - libglut-dev
        - libxi-dev
        - libglib2.0-dev

    - workdir: /opt

    - run:
        - curl -O https://afni.nimh.nih.gov/pub/dist/tgz/linux_ubuntu_24_64.tgz
        - tar -xf linux_ubuntu_24_64.tgz
        - mv linux_ubuntu_24_64 /usr/local/abin
        - rm -f linux_ubuntu_24_64.tgz

    - environment:
        PATH: /usr/local/abin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:~/.local/bin
        R_LIBS: /usr/local/share/R-4.3

    - run:
        - curl -O https://afni.nimh.nih.gov/pub/dist/tgz/package_libs/linux_ubuntu_24_R-4.3_libs.tgz
        - tar -xf linux_ubuntu_24_R-4.3_libs.tgz
        - mv linux_ubuntu_24_R-4.3_libs /usr/local/share/R-4.3
        - rm -f linux_ubuntu_24_R-4.3_libs.tgz

    - run:
        - "@afni_R_package_install ALL"

    - template:
        name: freesurfer
        version: 7.4.1

    - environment:
        SUBJECTS_DIR: "~/freesurfer-subjects-dir"
        DEPLOY_PATH: /usr/local/abin/

    - copy: dependencies.R /opt
    - copy: test.sh /test.sh
    - copy: test.tgz /opt/test.tgz
    - copy: license.txt /opt/freesurfer-7.4.1/license.txt

    - run:
        - Rscript /opt/dependencies.R

    - workdir: /opt

deploy:
  path:
    - /usr/local/abin/

readme: |-
  ----------------------------------
  ## afni/{{ context.version }} ##
  AFNI (Analysis of Functional NeuroImages) is a suite of C programs for processing, analyzing, and displaying functional MRI (fMRI) data.

  Example:
  ```
  afni -h
  3dinfo -h
  suma -h
  ```

  More documentation can be found here: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/

  To run container outside of this environment: ml afni/{{ context.version }}

  License: GPL-3.0 (https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu20.html)

  ----------------------------------

categories:
  - "functional imaging"

gui_apps:
  - name: "sumaGUI"
    exec: "suma"