name: afni
version: 25.2.03
# https://afni.nimh.nih.gov/about_afni

copyright:
  - license: GPL-3.0
    url: https://afni.nimh.nih.gov/legal_info

architectures:
  - x86_64

build:
  kind: neurodocker
  base-image: afni/afni_make_build:AFNI_{{ context.version }}
  pkg-manager: apt

deploy:
  path:
    - /usr/local/abin/

readme: |-
  ----------------------------------
  ## afni/{{ context.version }} ##
  AFNI (Analysis of Functional NeuroImages) is a suite of C programs for processing, analyzing, and displaying functional MRI (fMRI) data.

  Example:
  ```
  afni -h
  3dinfo -h
  suma -h
  ```

  More documentation can be found here: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/

  To run container outside of this environment: ml afni/{{ context.version }}

  License: GPL-3.0 (https://afni.nimh.nih.gov/legal_info)

  ----------------------------------

categories:
  - "functional imaging"

gui_apps:
  - name: "sumaGUI"
    exec: "suma"