name: mrtrix3tissue
version: "5.2.9"

copyright:
  - license: MPL-2.0
    url: https://github.com/3Tissue/MRtrix3Tissue/blob/master/LICENCE.txt

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ghcr.io/neurodesk/caid/fsl_6.0.3:20200905
  pkg-manager: apt

  directives:
    - template:
        name: mrtrix3
        version: "3Tissue_v{{ context.version }}"
        method: source
        repo: https://github.com/3Tissue/MRtrix3Tissue.git
        install_path: /opt/mrtrix3tissue-{{ context.version }}
        build_processes: "1"

deploy:
  path:
    - /opt/mrtrix3tissue-{{ context.version }}/bin/

readme: |
  ----------------------------------
  ## mrtrix3tissue/{{ context.version }} ##
  MRtrix3Tissue is a fork of the MRtrix3 project. It adds capabilities for 3-Tissue CSD modelling and analysis to a complete version of MRtrix3. More information can be found on the official website at https://3Tissue.github.io.

  Example:
  ```
  mrconvert --version
  ```

  Build details follow the official install guidance:
  https://3tissue.github.io/doc/install/

  To run container outside of this environment: ml mrtrix3tissue/{{ context.version }}

  ----------------------------------

categories:
  - diffusion imaging
