name: niimath
version: 1.0.0

variables:
  github_url: https://github.com/rordenlab/niimath.git
  revision: 5876e5bc573ef37fb9243566df4d561b8c16cea4

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker

  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - install: build-essential git libz-dev file
    # Do the build and install on a layer so we can remove it later
    - run:
        - git clone {{ context.github_url }} /tmp/niimath
        - cd /tmp/niimath
        - git reset --hard {{ context.revision }}
        - cd ./src
        # Build a static binary
        - make static -j{{ parallel_jobs }}
        - cp niimath /usr/bin
        - rm -rf /tmp/niimath

deploy:
  bins:
    - niimath
