name: manual-build

on:
  workflow_dispatch:
    inputs:
      applications:
        description: 'Applications (comma separated)'
        required: true
        type: string
      runner:
        description: 'Runner'
        required: true
        type: choice
        options: 
        - "ubuntu-22.04"
        - "self-hosted"
      force_push_ghcr:
        description: 'Force push to GHCR'
        required: false
        type: boolean
      force_push_dockerhub:
        description: 'Force push to DockerHub'
        required: false
        type: boolean
      force_upload_nectar:
        description: 'Force upload to Nectar'
        required: false
        type: boolean
      force_upload_s3:
        description: 'Force upload to S3'
        required: false
        type: boolean

jobs:
  list-apps:
    runs-on: ubuntu-22.04
    outputs:
      app_list: ${{ steps.process_app_list.outputs.app_list }}
      runner: ${{ steps.select_runner.outputs.runner }}
      force_push_ghcr: ${{ steps.build_inputs.outputs.force_push_ghcr }}
      force_push_dockerhub: ${{ steps.build_inputs.outputs.force_push_dockerhub }}
      force_upload_nectar: ${{ steps.build_inputs.outputs.force_upload_nectar }}
      force_upload_s3: ${{ steps.build_inputs.outputs.force_upload_s3 }}
    steps:
    - name: Process input list of applications
      id: process_app_list
      run: |
        app_list="$(echo "${{ github.event.inputs.applications }}" | tr -d " " | jq -rcR 'split(",")')"
        echo "app_list=${app_list}"
        echo "app_list=${app_list}" >> $GITHUB_OUTPUT
    - name: Select runner
      id: select_runner
      run: |
        runner="${{ github.event.inputs.runner }}"
        echo "runner=${runner}"
        echo "runner=${runner}" >> $GITHUB_OUTPUT
    - name: Set build inputs
      id: build_inputs
      run: |
        echo "force_push_ghcr=${{ github.event.inputs.force_push_ghcr }}" >> $GITHUB_OUTPUT
        echo "force_push_dockerhub=${{ github.event.inputs.force_push_dockerhub }}" >> $GITHUB_OUTPUT
        echo "force_upload_nectar=${{ github.event.inputs.force_upload_nectar }}" >> $GITHUB_OUTPUT
        echo "force_upload_s3=${{ github.event.inputs.force_upload_s3 }}" >> $GITHUB_OUTPUT

  build-app:
    needs: list-apps
    strategy:
      fail-fast: false
      matrix:
        application: ${{ fromJSON(needs.list-apps.outputs.app_list) }}
    uses: ./.github/workflows/build-app.yml
    with:
      application: ${{ matrix.application }}
      runner: ${{ needs.list-apps.outputs.runner }}
      # force_push_ghcr: ${{ needs.list-apps.outputs.force_push_ghcr }}
      # force_push_dockerhub: ${{ needs.list-apps.outputs.force_push_dockerhub }}
      # force_upload_nectar: ${{ needs.list-apps.outputs.force_upload_nectar }}
      # force_upload_s3: ${{ needs.list-apps.outputs.force_upload_s3 }}
    secrets: inherit