name: Process Contribution Issues

on:
  issues:
    types: [opened]

jobs:
  process-contribution:
    if: contains(github.event.issue.title, '[CONTRIBUTION]')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Parse YAML from issue body
        id: parse-yaml
        uses: actions/github-script@v7
        with:
          script: |
            const yaml = require('js-yaml');
            const issueBody = context.payload.issue.body;

            // Extract YAML content from issue body
            const yamlRegex = /```yaml\n([\s\S]*?)\n```/;
            const match = issueBody.match(yamlRegex);

            if (!match) {
              core.setFailed('No YAML content found in issue body');
              return;
            }

            try {
              const yamlContent = match[1];
              const parsedYaml = yaml.load(yamlContent);
              
              if (!parsedYaml.name) {
                core.setFailed('YAML must contain a "name" field');
                return;
              }
              
              core.setOutput('yaml_content', yamlContent);
              core.setOutput('name', parsedYaml.name);
              core.setOutput('parsed', JSON.stringify(parsedYaml));
            } catch (error) {
              core.setFailed(`Failed to parse YAML: ${error.message}`);
            }

      - name: Create branch name
        id: create-branch
        run: |
          BRANCH_NAME="contribution-${{ github.event.issue.number }}-${{ steps.parse-yaml.outputs.name }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{ steps.create-branch.outputs.branch_name }}

      - name: Check if file exists
        id: check-file
        run: |
          FILE_PATH="recipes/${{ steps.parse-yaml.outputs.name }}/build.yaml"
          if [ -f "$FILE_PATH" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
            echo "file_path=$FILE_PATH" >> $GITHUB_OUTPUT
            echo "action=update" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
            echo "file_path=$FILE_PATH" >> $GITHUB_OUTPUT
            echo "action=add" >> $GITHUB_OUTPUT
          fi

      - name: Create recipe file
        run: |
          RECIPE_DIR="recipes/${{ steps.parse-yaml.outputs.name }}"
          mkdir -p "$RECIPE_DIR"

          cat > "$RECIPE_DIR/build.yaml" << 'EOF'
          ${{ steps.parse-yaml.outputs.yaml_content }}
          EOF

      - name: Commit changes
        run: |
          git add recipes/
          git commit --author="${{ github.event.issue.user.login }} <${{ github.event.issue.user.id }}+${{ github.event.issue.user.login }}@users.noreply.github.com>" -m "${{ steps.check-file.outputs.action == 'add' && 'Add' || 'Update' }} recipe for ${{ steps.parse-yaml.outputs.name }} from issue #${{ github.event.issue.number }}"

      - name: Push branch
        run: |
          git push origin ${{ steps.create-branch.outputs.branch_name }}

      - name: Create pull request
        id: create-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${{ steps.check-file.outputs.action == 'add' && 'Add' || 'Update' }} recipe for ${{ steps.parse-yaml.outputs.name }}`,
              body: `This PR was automatically generated from issue #${{ github.event.issue.number }}.

              ## Summary
              - ${{ steps.check-file.outputs.action == 'add' && 'Adds new' || 'Updates existing' }} recipe for \`${{ steps.parse-yaml.outputs.name }}\`
              - Recipe file: \`${{ steps.check-file.outputs.file_path }}\`

              ## YAML Content
              \`\`\`yaml
              ${{ steps.parse-yaml.outputs.yaml_content }}
              \`\`\`

              Closes #${{ github.event.issue.number }}`,
              head: '${{ steps.create-branch.outputs.branch_name }}',
              base: 'master'
            });

            core.setOutput('pr_number', pr.number);
            core.setOutput('pr_url', pr.html_url);

      - name: Comment on issue with PR link
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✅ A pull request has been automatically created for your contribution!

              🔗 Pull Request: #${{ steps.create-pr.outputs.pr_number }}
              
              The recipe for \`${{ steps.parse-yaml.outputs.name }}\` has been ${{ steps.check-file.outputs.action == 'add' && 'added' || 'updated' }} in the PR. A maintainer will review and merge it soon.
              
              Thank you for your contribution! 🎉`
            });
